### ISSUE TITLE
Export type `IGiscusProps`

### ISSUE THREAD

**Issue by deadcoder0904** [giscus/react-giscus#3]
This would allow adding type support for `mapping` using `IGiscusProps.mapping` directly as my `mapping` prop comes from `parent`.

**Comment by deadcoder0904** [comment]
What's the difference between `mapping` & `term`? Both look same.

**Comment by laymonage** [comment]
@deadcoder0904 I don't think exporting the type is necessary, you can always do:

```ts
import type { ComponentProps } from "react";
import Giscus from "react-giscus";

const giscusProps: ComponentProps<typeof Giscus> = ...
```

`mapping` is some sort of enum for the mapping options, while `term` is the value for the mapping. I also use `term` for `mapping="number"`, so it's not always the title. I admit I could've done a better job there, but oh well...

**Comment by deadcoder0904** [comment]
@laymonage I think Next.js allows for types to be exported. Not sure what's the harm in exporting types?

I've kept `term` empty, I hope it's not a problem. Bdw, I can't find what to set for :

```ts
data-repo-id="[ENTER REPO ID HERE]"
data-category="[ENTER CATEGORY NAME HERE]"
data-category-id="[ENTER CATEGORY ID HERE]"
```

**Comment by laymonage** [comment]
There's no harm I suppose, just not my preference. I can export it if you need it.

## [Usage](https://github.com/giscus/react-giscus#usage)

Follow the instructions on [the website](https://giscus.app) and put the respective attributes of the shown `<script>` tag as props to the `Giscus` component.

**Comment by deadcoder0904** [comment]
> I can export it if you need it, but I can only look into it on the weekend. If you need it urgently, you can use the above method.

Yeah, definitely love to have it as I'm duplicating this code in 2 places:

```ts
type Mapping = 'number' | 'title' | 'pathname' | 'url' | 'og:title' | 'specific'
```

Yes, I read that but can't seem to find any info about those 3 parameters. I also checked out your repo but it contains random numbers & I don't know the origin where they came from. Would love to know where I can find them as it's not mentioned in the docs either & I'm currently implementing Giscus?

**Comment by deadcoder0904** [comment]
I'm not saying it's a Next.js limitation but see how Next.js does it for their type exports:

```ts
import type { AppProps } from 'next/app'
```

**Comment by laymonage** [comment]
Temporary solution:

```ts
export type IGiscusProps = ComponentProps<typeof Giscus>;
export type Mapping = IGiscusProps["mapping"];
```

It's set in the following code:
https://github.com/laymonage/giscus/blob/main/components/Configuration.tsx#L144-L153

Which, at the end, will call GitHub's API to retrieve the values: https://github.com/laymonage/giscus/blob/main/services/github/getDiscussionCategories.ts

It is necessary because they are needed for creating a new Discussion (which cannot use repository `owner/repo` and category name). See https://docs.github.com/en/graphql/guides/using-the-graphql-api-for-discussions#creatediscussion

> I also checked out your repo but it contains random numbers & I don't know the origin where they came from. Would love to know where I can find them as it's not mentioned in the docs either & I'm currently implementing Giscus?

Not sure what you mean by "random numbers". I don't mention it in the docs because I consider it to be an internal thing and most users don't need to worry about it. Once you type in your repository name and select the discussion category in the configuration guide, the values are automatically set for you.

![image](https://user-images.githubusercontent.com/6379424/127306473-7fceb0cf-e153-476a-87c5-2cb23093fdaf.png)

**Comment by deadcoder0904** [comment]
>  Once you type in your repository name and select the discussion category in the configuration guide, the values are automatically set for you.

I didn't know I had to set this up. I just scrolled & scrolled like a fool haha. Thank you :)

Bdw, do store the `theme` in `localStorage` on https://giscus.app/ as it keeps going back to light theme 🤣

**Comment by laymonage** [comment]
Closing this in favor of https://github.com/giscus/giscus-component.
